# Makefile for SSBC
# Developed for CSCI 261 by P. Walsh Feb 2010 (pwalsh@malun1.mala.bc.ca) 
# Copyright P. Walsh
#// Sami Al-Qusus   Nov 2018   Modified for MMA 

# Targets:
#	interactive: (default) run simulator
#	runtest: run all the tests (tinpKey and tinpMac)

interactive:
	./mma.pl

runtest: 
	@csh .batch_test 
	-more log
