// Include file with control unit parameters automatically generated by paramParam`Gen.pl 
// P. Walsh Nov 2016 
// Sami Al-Qusus   Nov 2018   Modified for MMA 
`define INIT0 0
`define INIT1 1
`define INIT2 2
`define INIT3 3
`define LDA0 4
`define LDA1 5
`define LDA2 6
`define LDA3 7
`define LDA4 8
`define STO0 9
`define STO1 10
`define STO2 11
`define ADD0 12
`define ADD1 13
`define ADD2 14
`define ADD3 15
`define ADD4 16
`define ADD5 17
`define ADD6 18
`define SUB0 19
`define SUB1 20
`define SUB2 21
`define SUB3 22
`define SUB4 23
`define SUB5 24
`define SUB6 25
`define JNE0 26
`define JNE1 27
`define JMP0 28
`define JMP1 29
