#!/usr/bin/perl
#controlParamGen.pl
#Perl script to generate labels for the control unit

open(fh, ">", "controlParam.v") or die $!;

print(fh "// Include file with control unit parameters automatically generated by paramParam`Gen.pl \n");
print(fh "// P. Walsh Nov 2016 \n  \n");

$MAX=5;
@arr = (INIT, LDA, STO, ADD, SUB, JMP, JNE);
$j=0;
for ($k=0; $k<=$#arr; $k++) {
   for ($i=0; $i<$MAX; $i++) {
      print(fh "`define $arr[$k]", $i, " ", $j, "\n");
      $j++;
   }
}
close(fh);
